### ISSUE TITLE
Loop error?

### ISSUE THREAD

**Issue by gustavo-eduard** [JohannesEbke/aws_list_all#13] opened 2019-05-14 15:44 UTC
aws-list-all query --service ec2 --operation DescribeVpcs --directory data --verbose                   
Building set of queries to execute...
Service: ec2                          | Region: us-west-1       | Operation: DescribeVpcs
Service: ec2                          | Region: ap-northeast-2  | Operation: DescribeVpcs
Service: ec2                          | Region: us-west-2       | Operation: DescribeVpcs
Service: ec2                          | Region: ca-central-1    | Operation: DescribeVpcs
Service: ec2                          | Region: ap-south-1      | Operation: DescribeVpcs
Service: ec2                          | Region: ap-southeast-1  | Operation: DescribeVpcs
Service: ec2                          | Region: sa-east-1       | Operation: DescribeVpcs
Service: ec2                          | Region: us-east-2       | Operation: DescribeVpcs
Service: ec2                          | Region: eu-west-1       | Operation: DescribeVpcs
Service: ec2                          | Region: us-east-1       | Operation: DescribeVpcs
Service: ec2                          | Region: eu-central-1    | Operation: DescribeVpcs
Service: ec2                          | Region: ap-southeast-2  | Operation: DescribeVpcs
Service: ec2                          | Region: eu-west-2       | Operation: DescribeVpcs
Service: ec2                          | Region: eu-west-3       | Operation: DescribeVpcs
Service: ec2                          | Region: eu-north-1      | Operation: DescribeVpcs
Service: ec2                          | Region: ap-northeast-1  | Operation: DescribeVpcs
...done. Executing queries...

The task "...done. Executing queries..." gets in loop and never finish, any sugestion?

Thanks in advance

**Comment by fhut** [comment] 2019-05-17 09:46
Try to use ctrl+c. Is it a duplicate of https://github.com/JohannesEbke/aws_list_all/issues/7 ?

**Comment by JohannesEbke** [comment] 2019-07-28 19:41
@gustavo-eduard I think that was a duplicate of #7 , and there have been several fixes now. Could you try again?

**Comment by JohannesEbke** [comment] 2019-09-20 22:51
If you hit it again, let me know, but I think it was #7 .

**Closed by JohannesEbke** 2019-09-20 22:51 UTC
Labels: bug
